# Generated by Django 4.1.1 on 2022-09-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_primary_color_product_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='illustrators',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='recipe_authors',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
