# Generated by Django 4.1.1 on 2022-10-12 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_variation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_valute',
            new_name='variation_value',
        ),
    ]
