# Generated by Django 4.1.1 on 2022-09-27 14:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default=accounts.models.get_default_profileimage, max_length=255, null=True, upload_to=accounts.models.get_profile_image_filepath),
        ),
    ]
