# Generated by Django 4.1.1 on 2022-09-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='illustrators',
            field=models.CharField(default='Lexi Adams', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='recipe_authors',
            field=models.CharField(default='Ampersand Paris', max_length=100),
            preserve_default=False,
        ),
    ]
