# Generated by Django 4.1.1 on 2022-09-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_illustrators_category_recipe_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='illustrators',
        ),
        migrations.RemoveField(
            model_name='category',
            name='recipe_authors',
        ),
    ]
